### ISSUE TITLE
Doesn't fade placeholder for first image

### ISSUE THREAD

**Issue by J05HI** [juliomrqz/website#209]
Hello @juliomrqz 
Somehow the first image doesn't fade from the placeholder to the real image. It only works for the rest of the images. The transition should be smooth for the first one, too.
![2020-05-11_21-01-48](https://user-images.githubusercontent.com/16399787/81601504-45634800-93cb-11ea-8b33-02327ff33ebc.gif)
![2020-05-11_21-06-27](https://user-images.githubusercontent.com/16399787/81601644-8196a880-93cb-11ea-86d2-cda0746acd4f.gif)

**Comment by J05HI** [comment]
Hello @juliomrqz 
are there any news for this problem? It still exists.
Thank you!

**Comment by juliomrqz** [comment]
I haven't spent time yet to fix the bug because I think it's a small issue and there are more important things to build or test. If you have a solution, you can send a pull-request without any problem 🤓.

**Comment by juliomrqz** [comment]
@J05HI, this issue is now fixed by this commit b5a69eb998b7b2a7654e0ce23f67cc8926885bfd

**Comment by J05HI** [comment]
@juliomrqz
Great! It was a issue with the lazyload lib?

**Comment by juliomrqz** [comment]
No, it was this scoped attribute that was preventing the style to be applied to the child image of the parent component. https://github.com/juliomrqz/website/blob/da292c62104eb91f8af502ea958d149d4f7c5a1d/components/ImageResponsive.vue#L117

But, I also took advantage of the fix to replace vue-lazyload with a better alternative ([vanilla-lazyload](https://github.com/verlok/vanilla-lazyload))

**Comment by J05HI** [comment]
@juliomrqz
Ah, okay, great!
