### ISSUE TITLE
Improve Lighthouse Score

### ISSUE THREAD

**Issue by J05HI** [juliomrqz/website#210]
Hello @juliomrqz 
I've checked the lighthouse score of your website. Looks like there is some room for improvements 😉 
I would like to say thank you for the great work, too! I've learned a lot.

![image](https://user-images.githubusercontent.com/16399787/81831094-3ac8c000-953d-11ea-85d3-0bc6fa3f880a.png)

**Comment by juliomrqz** [comment]
Hello @J05HI. Thanks for your comment. I’m glad that you learned something from this website.

My latest lighthouse test shows the latest improvements

![image](https://user-images.githubusercontent.com/1911993/81908898-397caf00-95a0-11ea-8c79-68b477fe79ee.jpeg)
